server:
<<<<<<< HEAD
  port: 7000
spring:
  application:
    name: eureka-server1
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://server2:7001/eureka/
  instance:
    hostname: server1
    lease-renewal-interval-in-seconds: 20
    lease-expiration-duration-in-seconds: 90

  server:
    enable-self-preservation: false
=======
  port: 7002
spring.cloud.client.ip-adress: 192.168.55.26
spring:
  application:
    name: eureka-provider1
eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: http://server1:7000/eureka/,http://server2:7000/eureka/
  instance:
    hostname: localhost
>>>>>>> 469f2100c93efcf08d7432eec45b971b46aa40a8
